### ISSUE TITLE
ServoMotorXPulse should have information regarding minimum and maximum values

### ISSUE THREAD

**Issue by bruno-f-cruz** [harp-tech/device.behavior#13]
https://github.com/harp-tech/device.behavior/blob/3ff429b3e19bee1c451059667a372b393c7d10bd/device.yml#L343

Currently, when certain values are passed (e.g. <5 ) the board returns an error message.

**Comment by filcarv** [comment]
These are the current limits running in firmware:

REG_MOTOR_OUT2_PERIOD   if (reg < 2 || reg > 65534)
REG_MOTOR_OUT2_PULSE    if (reg < 6 || reg > 65530)

REG_MOTOR_OUT3_PERIOD   if (reg < 2 || reg > 65534)
REG_MOTOR_OUT3_PULSE    if (reg < 6 || reg > 65530)
